
services:
  frontend:
    # restart: always
    hostname: frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    env_file:
      - ./frontend/.env
    ports:
      - "80:80"

  backend:
    # restart: always
    hostname: backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "5100:5100"