// export { default } from "./userControllers";
export { default as userControllers } from "./userController";
export { default as rolControllers } from "./rolController";
export { default as localControllers } from "./localController";
export { default as empadminController } from "./empadminController";
export { default as userlocalController } from "./userlocalController";
export { default as inputvalueController } from "./inputvalueController";
export { default as reportController } from "./reportController";
export { default as questionController } from "./questionController";
export { default as clasificationController } from "./clasificationController";
export { default as alertController } from "./alertController";
export { default as chartController } from "./chartController";
export { default as predictiveModelController } from "./predictiveModelController";
export { default as SuggestionController } from "./suggestionController";
